pipeline:
  sample:
    image: python:3.6.2-stretch
    commands:
      - python3 test.py
  prepare:
    image: python:3.6.2-stretch
    commands:
      - bash auto.sh
  docker:
    image: plugins/docker
    environment:
      - PLUGIN_DRY_RUN=1
      - PLUGIN_ENV_FILE=DRONE_ENV
    dockerfile: Dockerfile
  test:
    image: docker:17.05.0-ce-dind
    privileged: true
    commands:
      - /usr/local/bin/dockerd --data-root /var/lib/docker && . ./DRONE_ENV && /usr/local/bin/docker run --rm python:3.6.2-stretch echo hello $PLUGIN_TAG
  updatesite:
    image: plugins/webhook
    urls:
      - http://192.168.100.43:5001/hook
  notify:
    image: drillster/drone-email
    host: 192.168.1.247
    port: 25
    skip_verify: true
    from: drone@genouest.org
    recipients: [ olivier.sallou@irisa.fr ]
    recipients_only: true
    when:
      status: [ success, changed, failure ]
