pipeline:
  sample:
    image: python:3.6.2-stretch
    commands:
      - python3 test.py
      - cat /etc/hosts
      - curl -v https://openstack-192-168-100-43.genouest.org/v1/_ping
      - echo $${MYSECRET}
    extra_hosts:
        - "openstack-192-168-100-43.genouest.org:192.168.100.1"
    secrets: [mysecret]
  prepare:
    image: python:3.6.2-stretch
    commands:
      - bash auto.sh
  pretest:
    image: docker:17.05.0-ce-dind
    privileged: true
    commands:
      - ./test.sh
    extra_hosts:
        - "openstack-192-168-100-43.genouest.org:192.168.100.1"
    secrets: [docker_username, docker_password]
  docker:
    image: plugins/docker
    environment:
      # - PLUGIN_DRY_RUN=1
      - PLUGIN_ENV_FILE=DRONE_ENV
    dockerfile: Dockerfile
    custom_dns: 192.168.100.43
    extra_hosts:
        - "openstack-192-168-100-43.genouest.org:192.168.100.1"
    secrets: [docker_username, docker_password]
  test:
    image: docker:17.05.0-ce-dind
    privileged: true
    commands:
      - ./test.sh
    extra_hosts:
        - "openstack-192-168-100-43.genouest.org:192.168.100.1"
  updatesite:
    image: plugins/webhook
    urls:
      - http://192.168.100.43:5001/hook
  notify:
    image: drillster/drone-email
    host: 192.168.1.247
    port: 25
    skip_verify: true
    from: drone@genouest.org
    recipients: [ olivier.sallou@irisa.fr ]
    recipients_only: true
    when:
      status: [ success, changed, failure ]
