pipeline:
  sample:
    image: python:3.6.2-stretch
    commands:
      - python3 test.py
      - cat /etc/hosts
    extra_hosts:
        - "openstack-192-168-100-43.genouest.org:192.168.100.1"
  prepare:
    image: python:3.6.2-stretch
    commands:
      - bash ./ci/auto.sh
    when:
      branch: master


  checkspec:
    image: python:3.6.2-stretch
    environment:
        - BIOCONTAINERS_URL=http://192.168.100.43:3001/hook
    commands:
        - pip install dockerfile-parse requests
        - . ./DRONE_ENV && python ci/container_spec_check.py $DOCKERFILE
    custom_dns: 192.168.100.43
    extra_hosts:
        - "openstack-192-168-100-43.genouest.org:192.168.100.1"
    secrets: [github_status_token]
    when:
      branch: master


  docker:
    image: plugins/docker
    environment:
      # - PLUGIN_DRY_RUN=1
      - PLUGIN_ENV_FILE=DRONE_ENV
      - DOCKER_LAUNCH_DEBUG=true
      - GODEBUG=netdns=cgo
    dockerfile: Dockerfile
    custom_dns: 192.168.100.43
    extra_hosts:
        - "openstack-192-168-100-43.genouest.org:192.168.100.1"
    secrets: [docker_username, docker_password]
    when:
      branch: master


  test:
    image: docker:17.05.0-ce-dind
    privileged: true
    environment:
        - GODEBUG=netdns=cgo
    commands:
      - bash ./ci/test.sh
    extra_hosts:
        - "openstack-192-168-100-43.genouest.org:192.168.100.1"
    when:
      branch: master


  callwebupdate:
    image: python:3.6.2-stretch
    environment:
        - BIOCONTAINERS_URL=http://192.168.100.43:3001/hook
    commands:
        - pip install dockerfile-parse requests
        - . ./DRONE_ENV && python ./ci/notify.py $DOCKERFILE
    when:
        branch: master

  notify:
    image: drillster/drone-email
    host: 192.168.100.43
    port: 1025
    skip_verify: true
    from: drone@genouest.org
    recipients: [ olivier.sallou@irisa.fr ]
    recipients_only: true
    when:
      status: [ success, changed, failure ]
      branch: master
