pipeline:
  test:
    image: python:3.6.2-stretch
    commands:
      - python3 test.py
  prepare:
    image: python:3.6.2-stretch
    commands:
      - bash auto.sh
  docker:
    image: plugins/docker
    environment:
      - PLUGIN_DRY_RUN=1
      - PLUGIN_ENV_FILE=DRONE_ENV
    dockerfile: Dockerfile
  notify:
    image: drillster/drone-email
    host: 192.168.1.247
    skip_verify: true
    from: drone@genouest.org
    recipients: [ olivier.sallou@irisa.fr ]
    recipients_only: true
    when:
      status: [ changed, failure ]
