apiVersion: v1
kind: ReplicationController
metadata:
  name: biocontainers-ci-proxy
  labels:
    app: ci-proxy
    ci: github
spec:
  replicas: 1
  spec:
      containers:
      - name: ci-proxy
        image: osallou/biocontainer-ci-proxy
        ports:
        - containerPort: 9080
        env:
        - name: GITHUB_STATUS_TOKEN
          value:
        - name: DEBUG
          value: 0
        - name: JENKINS_URL
          value:
