apiVersion: v1
kind: Service
metadata:
  name: ci-proxy-svc-web
  labels:
    app: ci-proxy
spec:
  type: NodePort
  ports:
   - name: http
     port: 9080
     nodePort: 39080
  selector:
    app: ci-proxy
