FROM debian

LABEL version="2" \
  software.version="1.4.3" \
  description="bla bla" \
  container.name="conttest" \
  software="conttest1" \
  tags="proto"

RUN echo "test build subdir payload 115"
RUN apt-get update
RUN apt-get install -y curl
