FROM debian

LABEL version="2" \
  software.version="1.4.3" \
  container.name="conttest" \
  software="conttest1" \
  tags="proto"

RUN echo "test build subdir payload 110"
RUN apt-get update
RUN apt-get install -y curl
